AWSTemplateFormatVersion: 2010-09-09
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
Resources: 
    
    myDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                - DomainName: 'stack1-s3bucketstatic-1hzj0nrpdllk4.s3.amazonaws.com'
                  Id: S3Origin
                  CustomOriginConfig:
                    HTTPPort: '80'
                    HTTPSPort: '443'
                    OriginProtocolPolicy: http-only
            Enabled: true
            DefaultRootObject: index.html
            DefaultCacheBehavior:
                AllowedMethods:
                - GET
                - HEAD
                TargetOriginId: S3Origin
                ForwardedValues:
                    QueryString: 'true'
                    Cookies:
                        Forward: none
                TrustedSigners:
                - 1234567890EX
                - 1234567891EX
                ViewerProtocolPolicy: allow-all



                